---
abstract: "interface to PAUSE's module permissions file (06perms.txt)"
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  File::Slurp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PAUSE-Permissions
requires:
  File::HomeDir: 0
  File::Spec::Functions: 0
  HTTP::Tiny: 0
  Moo: 0
  autodie: 0
  feature: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/PAUSE-Permissions
  repository: https://github.com/neilbowers/PAUSE-Permissions.git
version: 0.05
